version: '3.8'

services:
  php:
    image: php:8.1-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8081:80"
